In [0]:
import pandas as pd  # loading the csv file

In [0]:
# now reading band data file
df=pd.read_csv('bank.csv')

In [4]:
# printing some top data
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
# removing unwanted data or columns
actual_data=df.iloc[:,3:]

In [0]:
# features extract from all remaining dats
features=actual_data.iloc[:,0:10].values

In [0]:
# labels 
label=actual_data.iloc[:,10].values

# Categorical Data

In [0]:
# changing data from string to numeric
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [0]:
# transforming particular column data (not numeric) into numeric one
country=LabelEncoder()
gender=LabelEncoder()

In [0]:
# transforming country data
features[:,1]=country.fit_transform(features[:,1])

In [11]:
features

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
features[:,2]=gender.fit_transform(features[:,2])

In [14]:
features # here female is 0 and male is 1

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
# now creating the dummy variables
content=OneHotEncoder(categorical_features=[1])

In [16]:
features=content.fit_transform(features).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
#features.astype(int)

In [0]:
features=features[:,1:]

In [0]:
# converting data into testing
from sklearn.model_selection import train_test_split

In [0]:
X,x,Y,y=train_test_split(features,label,test_size=0.2)

In [0]:
# applying feature scaling
from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler() # calling feature scaling 

In [0]:
# transforming training data only
X=sc.fit_transform(X)

In [0]:
# testing only needs to be transfor but not fit
x=sc.transform(x)

### till now we do the data processing

## Now we apply ANN

In [25]:
import keras

Using TensorFlow backend.


In [0]:
# to create ANN model
from keras.models import Sequential  # ANN initialize


In [0]:
# to fill data in each layer
from keras.layers import Dense # clf fit 

In [28]:
# calling ANN model as classifier
clf=Sequential()  # a frame for desiging ANN model

W0623 12:32:54.128274 140699074926464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [29]:
# now time for adding first hidden layers with input attribute / layer
clf.add(Dense(units=6,activation='relu',kernel_initializer='glorot_uniform',input_shape=(11,)))

W0623 12:32:54.680364 140699074926464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0623 12:32:54.694641 140699074926464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
# now adding second hidden layer
clf.add(Dense(units=6,activation='relu',kernel_initializer='glorot_uniform'))

In [0]:
# now finalizing output layer
clf.add(Dense(units=1,activation='sigmoid'))

In [0]:
# compile the created model
clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# optimizer --stoachtis gradi , loss == multiple output compare , metrics = accuracy in 
# each step

In [35]:
# fitting features and label data
clf.fit(X,Y,batch_size=10,epochs=100)

W0623 12:34:44.505807 140699074926464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.5098 - acc: 0.7914
Epoch 2/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4380 - acc: 0.7959
Epoch 3/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4125 - acc: 0.8076
Epoch 4/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3875 - acc: 0.8152
Epoch 5/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3730 - acc: 0.8179
Epoch 6/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3621 - acc: 0.8404
Epoch 7/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3540 - acc: 0.8551
Epoch 8/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3494 - acc: 0.8581
Epoch 9/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3458 - acc: 0.8570
Epoch 10/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3433 - acc: 0.8599

In [0]:
# now time for prediction
y_predict=clf.predict(x)
for i in range(len(y_predict)):
  if y_predict[i] > 0.5:
    y_predict[i] = 1
  else:
    y_predict[i] = 0
y_predict=y_predict.astype(int)    

In [81]:
y_predict

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [82]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [0]:
from sklearn.metrics import accuracy_score  # importing sklearn.metrics for calculating accuracy score
score=accuracy_score(y,y_predict)

In [86]:
score  # percentage of score

0.857